channels:
  - defaults
  - conda-forge
  - phumke
dependencies:
  - python=3.6
  - dash=1.2.0
  - dash-bootstrap-components=0.7.1
  - dash-daq=0.1.7
  - eli5=0.10.1
  - pandas=0.23.4
  - py-xgboost=0.90
  - python-graphviz=0.12
  - shap=0.30.0
